#!/usr/bin/env ruby

require 'colorize'
require 'octokit'
require 'yaml'

class Diff
  def initialize(old_array, new_array)
    @old_array = old_array
    @new_array = new_array
    @union = @old_array | @new_array
    @union.sort_by! { |elem| elem.downcase }
  end

  def additions
    @new_array - @old_array
  end

  def removals
    @old_array - @new_array
  end

  def pretty_print
    @union.map do |elem|
      if additions.include? elem
        elem = "+ #{elem}".colorize(:green)
      elsif removals.include? elem
        elem = "- #{elem}".colorize(:red)
      else
        elem = "  #{elem}"
      end
    end
  end
end

config = YAML.load_file('config/config.yaml')

client = Octokit::Client.new(access_token: config['access_token'])

owners_team = client.org_teams(config['org']).find { |team| team.name == 'Owners' }

current_owners = client.team_members(owners_team.id).map { |user| user.login }

requested_owners = YAML.load_file('config/owners.yaml')['owners']

diff = Diff.new(current_owners, requested_owners)

puts "Updating owners:"
puts diff.pretty_print

diff.additions.each do |username|
  client.add_team_member(owners_team.id, username)
end

diff.removals.each do |username|
  client.remove_team_member(owners_team.id, username)
end
