#!/usr/bin/env ruby

require 'octokit'
require 'yaml'

require './lib/array_diff'

config = YAML.load_file('config/config.yaml')

client = Octokit::Client.new(access_token: config['access_token'])

owners_team = client.org_teams(config['org']).find { |team| team.name == 'Owners' }

current_owners = client.team_members(owners_team.id).map { |user| user.login }

requested_owners = YAML.load_file('config/owners.yaml')['owners']

diff = ArrayDiff.new(current_owners, requested_owners)

puts "Updating owners:"
puts diff.pretty_print

diff.additions.each do |username|
  client.add_team_member(owners_team.id, username)
end

diff.removals.each do |username|
  client.remove_team_member(owners_team.id, username)
end
